name: restaurant_app
description: Restaurant Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^6.1.1
  cached_network_image: ^2.5.0
  cupertino_icons: ^1.0.2
  dio: ^3.0.10
  equatable: ^1.2.5
  flutter_bloc: ^6.1.1
  font_awesome_flutter: ^8.11.0
  pull_to_refresh: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.7
  bloc_test: ^7.1.0
  mockito: ^4.1.4

flutter:

  uses-material-design: true

  assets:
    - assets/local_restaurant.json
    - assets/images/main.jpg

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
